### PR TITLE
Feature/update nested component

### PR DESCRIPTION
**Pull request by NetoteaAndrei**
@plentymarkets/team-terra

Created showFullSelectionPath property, this property is a boolean and when is true will show the entire path on the selected node

### Definition of Done
Documentation
- [ ] Changelog
- [ ] Example (updated or created)
- [ ] JSDoc

Testing
- [ ] Person 1
- [ ] Person 2

Browser-Support
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by dantrau** [comment]
@NetoteaAndrei if you did not done so yet please check if your plugin works with current 3.0.0-beta version because of breaking changes. The changes of the `TerraNestedDataPickerComponent` may influence the `TerraCategoryPickerComponent`. Please test it in Shop Builder and Plugin Configuration of Ceres Plugin

**Comment by NetoteaAndrei** [comment]
@dantrau this changes for the TerraNestedDataPickerComponent will not influence the  TerraCategoryPickerComponent and will not influence nothing on old functionality, it's a feature for showing the entire path for selected node if you want, by default is like before will not show the entire path

**Comment by nappynapster** [comment]
Restart tests.

**Comment by pweyrich** [comment]
@NetoteaAndrei In the description of the Pull-Request there is a List of check boxes which represent our Definition of Done for this repository. Besides the two approves (which are enforced by github) all of the criteria listed in this definition must be checked before merging a pull request. 

In this case you missed out to update the corresponding example of the component. Hence your feature will not be described in our [components documentation](https://developers.plentymarkets.com/terra-doc/components).

We were also not able to test your feature in the different browsers..

For the next time, please make sure to respect the definition of done in this repository.

**Comment by dantrau** [comment]
@NetoteaAndrei v2.3.26 was published today

**Comment by NetoteaAndrei** [comment]
@dantrau  thank you.

**Pull request merged**
